---
title: "STAT400_Project"
author:
- name: Isaac Swope
- name: Benjamin Howland
date: "2026-4-29"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Front Matter

```{r, message = FALSE}
rm(list = ls())
# Libraries
library(tidyverse)
library(kableExtra)
library(leaflet)
library(caret)
library(stringr)
library(randomForest)
library(nnet)
library(mclogit)
library(MLmetrics)
library(patchwork)
```

```{r}
# data
Diap_raw <- read.csv("https://raw.githubusercontent.com/Swopei/STAT400proj_repo/refs/heads/main/Data/observations-700123.csv")
```


# Exploratory Data Analysis

```{r}
Diap <- Diap_raw %>%
  filter(quality_grade == "research",
         taxon_species_name != "",
         !is.na(latitude),
         !is.na(longitude)) %>%
  mutate(taxon_species_name = as.factor(taxon_species_name),
         observed_on = as.Date(observed_on),
         month = month(observed_on),
         cos_month = cos(2 * pi * month / 12),
         sin_month = sin(2 * pi * month / 12)) %>%
  group_by(taxon_species_name) %>%
  filter(n() >= 10) %>%
  ungroup()

Diap <- droplevels(Diap)

Diap_freq <- Diap %>%
  group_by(taxon_species_name) %>%
  summarise(
    count = n()
  ) %>%
  arrange(desc(count))

kable(Diap_freq)
```


```{r}
ggplot(data = Diap_freq,
       mapping = aes(x = reorder(taxon_species_name, count), y = count)) +
  geom_segment(aes(x = reorder(taxon_species_name, count), xend = reorder(taxon_species_name, count), 
                   y = 0, yend = count), 
               color = "forestgreen") +
  geom_point(color = "black") +
  scale_y_continuous(breaks = seq(0, 10000, by = 1000)) +
  coord_flip() +
  theme_minimal() +
  labs(x = "Species", y = "Count", title = "Species by Identified Observations")
```


```{r}
ggplot(data = Diap,
       mapping = aes(x = latitude, fill = taxon_species_name)) + 
  geom_histogram(binwidth = 0.25) +
  theme_minimal() +
  coord_flip() +
  labs(x = "Latitiude", y = "Count", fill = "Species")
```

```{r}
ggplot(data = Diap,
       mapping = aes(x = longitude, fill = taxon_species_name)) + 
  geom_histogram(binwidth = 1) +
  theme_minimal() +
  labs(x = "Longitude", y = "Count", fill = "Species")
```




```{r}

Diap_month <- Diap %>%
  group_by(month, taxon_species_name) %>%
  summarize(total = n())

Diap_month$month_abb <- month.abb[Diap_month$month]
Diap_month$month_abb <- factor(Diap_month$month_abb, levels = month.abb)

label_radius <- max(Diap_month$total)*1.5

ggplot(data = Diap_month, 
       mapping = aes(x = month_abb, y = total, fill = taxon_species_name)) +
  geom_bar(stat = "identity", width = 1, color = "white") + 
  geom_text(aes(y = label_radius, label = month_abb), 
            size = 4, 
            fontface = "bold") +
  coord_polar(start = 0) + 
  scale_y_continuous(limits = c(0, label_radius * 1.1), expand = c(0, 0)) +
  theme_minimal() +
  labs(title = "Monthly Totals of Diapensciaceae Observations", x = "", y = "") +
  theme(
    panel.grid = element_blank(), 
    axis.text.x = element_blank(), 
    axis.text.y = element_blank(), 
    axis.ticks = element_blank()
  )
```


```{r}

species_palette <- colorFactor(palette = "Set1", domain = Diap$taxon_species_name)

leaflet(Diap) %>%
  addProviderTiles(providers$Esri.WorldImagery) %>% 
  #addTiles() %>%
  addCircleMarkers(
    lng = ~longitude, 
    lat = ~latitude,
    color = ~species_palette(taxon_species_name),
    radius = 4,
    fillOpacity = 0.95,
    stroke = FALSE,
    popup = ~paste("<b>Species:</b>", taxon_species_name)
  ) %>%
  addLegend(
    pal = species_palette, 
    values = ~taxon_species_name, 
    title = "Species",
    position = "bottomright"
  )
```


# Generalized Linear Modeling

```{r}
model1 <- multinom(taxon_species_name ~ latitude + longitude + cos_month + sin_month, data = Diap)
model2 <- multinom(taxon_species_name ~ latitude * longitude + cos_month + sin_month, data = Diap)
model3 <- multinom(taxon_species_name ~ latitude + longitude + I(latitude^2) + I(longitude^2) + cos_month + sin_month, data = Diap)
model4 <- multinom(taxon_species_name ~ latitude * longitude + I(latitude^2) + I(longitude^2) + cos_month + sin_month, data = Diap)

pred1 <- predict(model1)
pred2 <- predict(model2)
pred3 <- predict(model3)
pred4 <- predict(model4)

y <- Diap$taxon_species_name
classes <- unique(y)

# Model 1
acc1 <- mean(pred1 == y)
f1_1 <- mean(sapply(classes, function(cl) {
  F1_Score(pred1 == cl, y == cl)
}), na.rm = TRUE)
aic1 <- AIC(model1)

# Model 2
acc2 <- mean(pred2 == y)
f1_2 <- mean(sapply(classes, function(cl) {
  F1_Score(pred2 == cl, y == cl)
}), na.rm = TRUE)
aic2 <- AIC(model2)

# Model 3
acc3 <- mean(pred3 == y)
f1_3 <- mean(sapply(classes, function(cl) {
  F1_Score(pred3 == cl, y == cl)
}), na.rm = TRUE)
aic3 <- AIC(model3)

# Model 4
acc4 <- mean(pred4 == y)
f1_4 <- mean(sapply(classes, function(cl) {
  F1_Score(pred4 == cl, y == cl)
}), na.rm = TRUE)
aic4 <- AIC(model4)

results <- data.frame(
  Model = c("Model 1", "Model 2", "Model 3", "Model 4"),
  AIC = c(aic1, aic2, aic3, aic4),
  Accuracy = c(acc1, acc2, acc3, acc4),
  Macro_F1 = c(f1_1, f1_2, f1_3, f1_4)
)

print(results)
```


```{r}
# Testing / Training Split
set.seed(40)
train_ind <- sample(1:nrow(Diap), floor(0.8*nrow(Diap)))
set.seed(NULL)

DiapTrain <- Diap[train_ind, ]
DiapTest <- Diap[-train_ind, ]
```

```{r}
Diap_glm <- multinom(taxon_species_name ~ latitude * longitude + I(latitude^2) + I(longitude^2) + cos_month + sin_month, data = DiapTrain)
Diap_glm_preds <- predict(Diap_glm, DiapTest)
conf_mat_glm <- confusionMatrix(Diap_glm_preds, DiapTest$taxon_species_name)
```

```{r}
conf_df_glm <- as.data.frame(conf_mat_glm$table)
conf_df_glm$Reference <- gsub("^([A-Z])[a-z]+", "\\1.", conf_df_glm$Reference)
conf_df_glm$Prediction <- gsub("^([A-Z])[a-z]+", "\\1.", conf_df_glm$Prediction)


ggplot(conf_df_glm, aes(x = Reference, y = Prediction, fill = Freq)) +
  geom_tile() +
  geom_text(aes(label = Freq), color = "white") +
  scale_fill_gradient(low = "blue", high = "red") +
  theme(
    axis.text.x = element_text(angle = 60, vjust = 1, hjust = 1, size = 10)
  ) +
  labs(title = "Species Classification Confusion Matrix",
       x = "Actual Species",
       y = "Predicted Species")
```

```{r}
# Extract the F1 score for each
f1_scores_glm <- conf_mat_glm$byClass[, "F1"]

# Calculate the Macro-F1 
macro_f1_glm <- mean(f1_scores_glm, na.rm = TRUE)
print(paste("Macro-F1 Score:", round(macro_f1_glm, 4)))

# Accuracy
print(paste("Accuracy:", round(conf_mat_glm$overall['Accuracy'], 4)))

#Kappa 
print(paste("Kappa:", round(conf_mat_glm$overall['Kappa'], 4)))
```


# Multilevel Modeling


# Machine Learning

```{r}
# Testing / Training Split

set.seed(40)
train_ind <- sample(1:nrow(Diap), floor(0.8*nrow(Diap)))
set.seed(NULL)

DiapTrain <- Diap[train_ind, ]
DiapTest <- Diap[-train_ind, ]
```

```{r}
Diap.rf <- randomForest(taxon_species_name ~ latitude + longitude + cos_month + sin_month, data = DiapTrain)
Diap.rf_preds <- predict(Diap.rf, DiapTest)
conf_mat_rf <- confusionMatrix(Diap.rf_preds, DiapTest$taxon_species_name)
```

```{r}
conf_df_rf <- as.data.frame(conf_mat_rf$table)
conf_df_rf$Reference <- gsub("^([A-Z])[a-z]+", "\\1.", conf_df_rf$Reference)
conf_df_rf$Prediction <- gsub("^([A-Z])[a-z]+", "\\1.", conf_df_rf$Prediction)


ggplot(conf_df_rf, aes(x = Reference, y = Prediction, fill = Freq)) +
  geom_tile() +
  geom_text(aes(label = Freq), color = "white") +
  scale_fill_gradient(low = "blue", high = "red") +
  theme(
    axis.text.x = element_text(angle = 60, vjust = 1, hjust = 1, size = 10)
  ) +
  labs(title = "Species Classification Confusion Matrix",
       x = "Actual Species",
       y = "Predicted Species")
```

```{r}
# Get F1 score for each
f1_scores_rf <- conf_mat_rf$byClass[, "F1"]

# Get the Macro-F1 
macro_f1_rf <- mean(f1_scores_rf, na.rm = TRUE)
print(paste("Macro-F1 Score:", round(macro_f1_rf, 4)))

# Accuracy
print(paste("Accuracy:", round(conf_mat_rf$overall['Accuracy'], 4)))

#Kappa 
print(paste("Kappa:", round(conf_mat_rf$overall['Kappa'], 4)))
```

```{r}
varImpPlot(Diap.rf)
```


